- practice_app/apps/advice/admin.py
- practice_app/apps/advice/models.py
- practice_app/apps/advice/templates/adviceHome.html
- practice_app/apps/advice/tests.py
- practice_app/apps/advice/urls.py
- practice_app/apps/advice/views.py
- **Database and Statistics**
The app now provides user statistics using the database. The information of the users is kept in the Advice Users table.
GET requests now also returns the statistics to display them on the home page.
- **Erroneous Requests**
The app now handles the erroneous requests. If the request contains bad input (e.g. 187 as age or jg98e as sex etc.) the app responds with status code 400 and the reason for the error as JSON. If the app fails to make a request to the MyHealthFinder API, it responds with status code 502 and the reason for the error as JSON.
- **Unit Tests**
The tests for the GET and POST methods are added. The tests test all possible values for the age, sex, tobaccoUse and sexuallyActive parameters.
**P.S.** The tests take a while (approximately 6 minutes …
> Advice App Database Support, Bad Input Handling, and Tests

- practice_app/apps/post/templates/postindex.html
- practice_app/apps/post/tests.py
- practice_app/apps/post/urls.py
- practice_app/apps/post/views.py
The app now provides support for weather forecast in Istanbul for external API task, you can see the temperature on the homepage. Also, I wrote the unit tests inside the tests.py file.
The code for the app needs to be reviewed by 2 people before merging as discussed in meeting 15.
> Post App: External API and Tests

- practice_app/apps/article/tests.py
- practice_app/apps/article/urls.py
The changes mentioned in [#126](https://github.com/bounswe/bounswe2022group6/issues/126) are made. 
Tests for article app is now running and working as expected.
> Article App: Test Enhancement

- practice_app/apps/advice/templates/adviceHome.html
A button that redirects to the home page is added.
> Added a back button to the advice home page.

- practice_app/apps/user/urls.py
- practice_app/apps/user/views.py
I have implemented the rest framework api's also.
> User App: minor updates about api

- practice_app/apps/drug_side_effects/templates/drug_side_effects_home.html
Drugs and Side Effects back button to the home page added to the top of the page as discussed.
> Drugs and Side Effects back button added to the top

- practice_app/apps/home/templates/home.html
The stylization of the buttons on the home page and their layout has been updated.
> Home Buttons

- practice_app/apps/home/templates/home.html
- practice_app/apps/report/admin.py
- practice_app/apps/report/apps.py
- practice_app/apps/report/forms.py
- practice_app/apps/report/models.py
- practice_app/apps/report/serializers.py
- practice_app/apps/report/templates/report.html
- practice_app/apps/report/tests.py
- practice_app/apps/report/urls.py
- practice_app/apps/report/views.py
- practice_app/practice_app/settings.py
- practice_app/practice_app/urls.py
I have added the report app, can you please review it?
> changes on report app

- Application/Backend/src/settings.py
- Application/Frontend/Dockerfile
- Application/Frontend/docker-compose.yml
- Application/Frontend/src/App.test.js
Dockerization for frontend workspace now should work
> Add dockerfile and docker-compose.yml for containerization

- Application/Frontend/Dockerfile
Minor update to lower image size of frontend container up to 67%
> Update frontend base image"

- Application/Backend/requirements.txt
- Application/Backend/src/settings.py
I have found and implemented the solution of the CORS error in a Django application.
> Solving the encountered CORS error

- Application/Backend/api_docs/profile_api_doc.json
- Application/Backend/src/accmgr/views.py
- Application/Backend/src/urls.py
This pull request will add documents for profile API's GET request.
> Add docs for profile details Postman documents

- Application/Backend/src/accmgr/views.py
- Application/Backend/src/urls.py
This API will return user profile details except the password hash when a sent a GET request.
> Add profile API to get user details

- Application/Frontend/src/pages/Home.js
- Application/Frontend/src/pages/home.module.css
I writed content and make some changes at design
> Home Page Changes

- Application/Mobile/pages/authantication/Login.js
- Application/Mobile/pages/authantication/SignUpScreen.js
> Login SignUp Pages API Problem Fixed!

- Application/Mobile/pages/authAPI.js
- Application/Mobile/pages/authantication/Login.js
- Application/Mobile/pages/authantication/SignUpScreen.js
> Birth Date static value problem fixed

- Application/Mobile/pages/home/HomeHeader.js
- Application/Mobile/pages/home/HomeScreen.js
- Application/Mobile/pages/navigation/DrawerNavigation.js
- Application/Mobile/pages/post/PostPreview.js
The home feed has:
- search bar
- chatbot icon
- refresh control
- post previews with labels
Please note that not all the buttons are functional right now.
> Added Home Feed

- Application/Backend/api_docs/profile_api_doc.json
- Application/Backend/src/accmgr/models.py
- Application/Backend/src/accmgr/tests.py
- Application/Backend/src/accmgr/views.py
The endpoints for the profile viewing and editing functionalities are implemented.
To receive the information of a user, the user has to be authenticated (logged in). If the user is authenticated, they can get all the information except the password hash by making a GET request to the profile or profile/ endpoint.
To change the information in an account, the user has to be authenticated (logged in). If the user is authenticated, they can change the information on their account by making a PATCH request to the profile or profile/ endpoint with the necessary form data present in the body of the request.
If a key (field name) is not present in the form data, it means that the value in the account will not change. If a key is present but its value is an empty string, it means that the value …
> Profile View/Edit Functionalities Implemented

- Application/Frontend/package.json
A bug that causes frontend to not compile has been fixed. Now, frontend should start without an issue.
> Fix react-icons bug

- Application/Backend/docker_backend/test_settings.py
- Application/Backend/src/accmgr/urls.py
- Application/Backend/src/contmgr/admin.py
- Application/Backend/src/contmgr/apps.py
- Application/Backend/src/contmgr/models.py
- Application/Backend/src/contmgr/tests.py
- Application/Backend/src/contmgr/urls.py
- Application/Backend/src/contmgr/views.py
- Application/Backend/src/settings.py
- Application/Backend/src/urls.py
The contmgr application and relevant links has been created. Also, the code of URL list has been refactored
> Add contmgr app, refactor code

- Application/Frontend/src/pages/Profile.js
Task that described in [the issue #300](https://github.com/bounswe/bounswe2022group6/issues/300) is completed. Form is divided into 2 part one for general users other one for doctor verification. If doctor is verified, an informative writing can be seen below the form.
The design is not completed yet, please review the functionality and let me know if there is a problem.
> Doctor verification is added.

- Application/Mobile/package-lock.json
- Application/Mobile/package.json
- Application/Mobile/pages/components/PhotoUpload.js
- Application/Mobile/yarn.lock
photo upload feature is implemented,
can be use anywhere as discussed
> file upload is done

- Application/Backend/api_docs/comment_api_doc.json
- Application/Backend/api_docs/content_vote_api_doc.json
- Application/Backend/api_docs/post_api_doc.json
This pull request is for merging documents and testcases for content manager.
Task List:
I have opened this pull request early to supply essential documents to other subgroups.
<b>Deadline:</b> 09.12.2022
> Add documents for content manager

- Application/Backend/src/contmgr/views.py
The view for creating a post now correctly accepts a list of labels in the form data sent in the request body.
> Added Label Addition to Post Creation View

- Application/Mobile/pages/authAPI.js
- Application/Mobile/pages/authentication/SignUpScreen.js
- Application/Mobile/pages/home/HomeFeed.js
- Application/Mobile/pages/post/PostPreview.js
- Application/Mobile/pages/search/FilterModal.js
- Application/Mobile/pages/search/SearchScreen.js
The backend connections for home feed and post search are established in this PR.
> Post Search & Home Feed Backend Connection Established

- Application/Mobile/pages/components/PhotoUpload.js
- Application/Mobile/pages/post/CreatePost.js
Reverts bounswe/bounswe2022group6#347
> Revert "Mobile/create post"

- Application/Backend/src/contmgr/models.py
- Application/Backend/src/contmgr/views.py
Labels are added to get post view and comment count field added to search and all posts endpoints.
> Post Views Updated

- Application/Frontend/src/components/ForumPost.js
- Application/Frontend/src/pages/Post.js
> hotfix for labels and comment count changes from backend

- Application/Mobile/pages/authAPI.js
- Application/Mobile/pages/home/HomeFeed.js
- Application/Mobile/pages/post/PostPreview.js
- Application/Mobile/pages/userAPI.js
> Vote Buttons Initialized

- deliverables/CMPE451_Customer_Presentation_Milestone_2.md
The executive summary section is added to the milestone 2 report. It includes the sub-sections, summary of the project status, changes made for improvement since milestone 1, and improvements planned for the remainder of the project.
> Executive Summary Section Added to Milestone 2 Report

- deliverables/CMPE451_Customer_Presentation_Milestone_2.md
The annotation section for the customer milestone 2 report is added. It birefly describes our current status and future plans for annotations.
> Added Annotation Section to the Customer Presentation Milestone 2

- deliverables/CMPE451_Customer_Presentation_Milestone_2.md
The section for work done towards W3C and ontology standards is added to the customer milestone 2.
> Added Standards Section to the Customer Milestone 2

- deliverables/CMPE451_Customer_Presentation_Milestone_2.md
The personal report and personal effort table of Yusuf Erdem Nacar is added to the customer milestone 2 report.
> Added Personal Report and Table of Yusuf Erdem Nacar to the Customer Milestone 2 Report

- Application/Mobile/ReadMe.md
ReadMe.md explains how to setup the Android application step by step for different development environments.
> Added ReadMe.md for the Mobile Folder

- Application/Backend/src/contmgr/models.py
- Application/Backend/src/contmgr/views.py
Endpoint API for edit comment/post has been added by PUT method. Nearly all of the sections except id's and owner can be changed with this new method. If no key in form has been given, old values are preserved. Also, a new database key, last_update_at, has been added to keep track of updates. Besides, there are refactors and changes in post method too.
Please note that tests and documents will be added via [Writing Content Manager's Documentation and Tests](https://github.com/bounswe/bounswe2022group6/issues/309)
> Edit Post Comment Endpoint Implementation Merge

- Application/Mobile/package-lock.json
- Application/Mobile/package.json
- Application/Mobile/pages/authAPI.js
- Application/Mobile/pages/authentication/Login.js
- Application/Mobile/pages/authentication/SignUpScreen.js
- Application/Mobile/pages/home/HomeFeed.js
- Application/Mobile/pages/home/HomeScreen.js
- Application/Mobile/pages/navigation/AppNavigation.js
- Application/Mobile/pages/navigation/DrawerNavigation.js
- Application/Mobile/pages/post/PostPreview.js
- Application/Mobile/pages/postAPI.js
- Application/Mobile/pages/userAPI.js
- Application/Mobile/yarn.lock
Users can use the app without logging in.
In the drawer, guests cannot see:
- Profile Page button
- Messages Screen
instead, they see
- Log in
- Sign up
buttons.
And guests cannot upvote/downvote posts.
> Guest Login is Implemented for Mobile

- Application/Mobile/pages/home/HomeFeed.js
- Application/Mobile/pages/post/PostPreview.js
Some enhancements & bug fixes are carried out in home feed and post previews:
**Added:**
- Activity Indicator (spinning loading animation) while fetching data.
- "Your feed is empty." text when the feed is empty.
**Bug Fixes:**
- A typo in API URL is fixed.
- Sometimes refreshing the home feed resulted in infinite loops. The inconsistent updating of the relevant states are fixed.
**Added:**
- When the post creation time on a post preview is clicked, the detailed timestamp is shown to give detailed information about when exactly a post is created. When it is clicked again, the previous text returns.
> Home Feed and Post Preview Enhancements

- Application/Backend/api_docs/comment_api_doc.json
- Application/Backend/api_docs/post_api_doc.json
- Application/Backend/api_docs/profile_api_doc.json
- Application/Backend/api_docs/search_api_doc.json
- Application/Backend/src/accmgr/models.py
- Application/Backend/src/accmgr/serializers.py
- Application/Backend/src/accmgr/tests.py
- Application/Backend/src/accmgr/views.py
- Application/Backend/src/contmgr/models.py
- Application/Backend/src/contmgr/serializers.py
- Application/Backend/src/contmgr/tests.py
- Application/Backend/src/contmgr/views.py
The content of the response to the GET requests for profile, post, and comment is enhanced. The data returned is now more detailed.
Compared to before, the details of the author of a post or comment are returned within the response of the GET post or comment also. This helps with determining if the author is a doctor or not.
In general, since the serializer is utilized, the responses have more detailed, recursive data.
The updated documentation are included besides the old form of the GET responses.
> Enhanced Response Data of Profile, Post and Comment Retrieval

- Application/Frontend/src/components/Comment.js
- Application/Frontend/src/components/ForumPost.js
- Application/Frontend/src/pages/Post.js
Some fields used in the responses are changed during the backend response enhancements, these changes required minor changes in some pages.
> Changes in frontend due to backend response enhancements

- Application/Mobile/pages/profile/EditProfileScreen.js
- Application/Mobile/pages/profileAPI.js
With this update, users can delete their accounts now.
Users can delete their accounts by going to their profile, then entering the profile editing page, and then clicking the delete account button at the very bottom. A dialog appears to confirm your request.
Note that deleting an account is dangerous and can not be undone.
> Delete Account Feature Implemented in Mobile

- Application/Backend/src/settings.py
- Application/Frontend/Dockerfile
- Application/Frontend/package.json
- Application/README.md
- Application/docker-compose.yml
Production code has been containerized for final milestone. It does not conflict with any of the development builds, and it is slightly more efficient and significantly more secure than development containers. Also, documentation for this code is written. It includes tutorials for both development and production builds, and includes essential parameters for .env files.
> Implementation Production Docker Code and Its Documentations

- Application/Frontend/src/components/Comment.js
- Application/Frontend/src/pages/Post.js
- Application/Frontend/src/services/Delete_Post_API.js
- Application/Frontend/src/services/Delete_comment_API.js
Integration of the post and comment endpoints has completed.
> Delete operation for post and comment

- Application/Mobile/pages/post/PostDetails.js
Post details did not have scroll functionality. It is fixed with this pR
> Hot Fix - Post Details do not have scrollview

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
The standards subsection of the progress section is added. It describes the the work towards the standards that are used in the project.
> Standards Part Added

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
The annotations subsection of the progress section is added. It describes the status of the annotations in our project.
> Annotations Part Added

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
The User Scenarios and Mockups subsection of the Project Artifacts is added. It includes scenarios and mockups from both previous semester and this semester.
> User Scenarios and Mockups

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
I added the use case, class and sequence diagrams to the report.
> UML diagrams added

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
The individual report and effort table of Yusuf Erdem Nacar is added.
> Added Yusuf Erdem Nacar's Individual Report and Effort Table

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
> API Endpoints are updated

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Added my summary of work performed and individual report to the final milestone.
> Work Performed & Individual Report - Hakan BALIK

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Screenshots of web have been added to the report.
> UI / UX of Frontend

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Added my summary of work performed and individual report to the final milestone.
> Final Milestone Report

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
The links to the backend unit tests are added.
> Added Backend Tests to the Unit Tests Section

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
The executive summary part is added to the milestone 3 report. It
includes the following sections:
* Summary of project status
* Status of the deliverables
* Final release notes
* Changes made and planned from the previous milestone
* Reflections from the final milestone demo
* What could be done differently?
> Executive Summary Part Added

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
I have added my personal data.
> Update CMPE451_Customer_Presentation_Milestone_3 on my contribution

- deliverables/CMPE451_Customer_Presentation_Milestone_3.md
> General/documentation/artun akdogan indıvıdual report
